version: '3.5'

services:
  web:
    image: 9e3u2f0b1/sent-template:latest
    container_name: web
    env_file: .env
    environment: 
      OPEN_BROWSER_AFTER_BUILD: "false"
    build:
      context: .
      dockerfile: docker/web/Dockerfile.development
    command: npm run dev
    tty: true
    ports:
      - '3000:3000'
      - '10000:10000'
    networks:
      - test-network

  storybook:
    container_name: storybook
    build:
      context: .
      dockerfile: docker/storybook/Dockerfile
    restart: unless-stopped
    command: npm run storybook
    ports:
      - '6006:6006'
    networks:
      - test-network

  test:
    container_name: test
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    environment:
      CYPRESS_BASE_URL: http://web:3000
    command: npm run test:headless
    depends_on:
      - web
    networks:
      - test-network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - web
    networks:
      - test-network

networks:
  test-network:
    name: test-network
    driver: bridge

volumes:
  node_modules:
