version: '3.5'

services:
  sent-template:
    image: 9e3u2f0b1/sent-template:latest
    build:
      context: .
      dockerfile: docker/web/Dockerfile.production
    command: npm run start
    env_file: .env
    restart: unless-stopped
    ports:
      - '3000:3000'
