on:
  pull_request:
    branches:
      - master

name: linters and tests
jobs:
  linters:
    name: linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm run install:prod:full
      - run: npm run eslint
      - run: npm run stylelint
      - run: npm run svelte:check

  tests:
    name: unit and integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: cp template.env .env
      - run: npm run install:prod:full
      - run: npm run fontello
      - run: npm run build
      - run: npm run test:prod

  container:
    name: build container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: cp template.env .env

      - name: build application
        run: npm run install:prod:full && npm run fontello && npm run build

      - name: setup Docker launcher
        uses: docker/setup-qemu-action@v1

      - name: setup Docker builder
        uses: docker/setup-buildx-action@v1

      - name: build Docker image
        uses: docker/build-push-action@v2
        with:
          tags: 9e3u2f0b1/sent-template:latest
          file: ./docker/web/Dockerfile.production
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          context: .

      - name: image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: image size
        uses: wemake-services/docker-image-size-limit@master
        with:
          image: '9e3u2f0b1/sent-template:latest'
          size: '200 MB'
